### ISSUE TITLE
Crashing with Electron 11

### ISSUE THREAD

**Issue by Isadorious** [Treverix/remote#2]
I'm using Electron 11.0.3 and trying to use custom electron titlebar. When trying to start my app, it crashes with the following stack trace. This seems to be related to issue 15 in electron remote https://github.com/electron/remote/issues/15

```
TypeError: process.electronBinding is not a function
    at Object.<anonymous> (\my-electron-app\node_modules\@treverix\remote\dist\src\main\objects-registry.js:3:24)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (\my-electron-app\node_modules\@treverix\remote\dist\src\main\server.js:8:44)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
```

**Comment by Treverix** [comment]
Thanks for reporting! Now that @electron/remote is fully functional, there's no use for this library anymore. 

All users should remove that from their dependencies and require `@electron/remote` again. The @treverix/custom-electron-titlebar project for which I created this fork has been updated too.
